### ISSUE TITLE
high window with uvf input (also uvf input path has depreciated)

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#30]
I have recently tried using the uvf cube input path in eppsilon, and there appears to be many things undefined in various parts of the code. I could give specifics, but there are *many* spots that failed, so I think it's best to pull it up in an interactive session with a recent FHD uvf cube.

**Comment by nicholebarry** [comment]
I didn't fix the problem, but I bypassed a lot of it. It was keyword passing and beam options that don't get used in the end. Still needs fixing, but my hacking *shouldn't* affect the results. 

The uvf input gave really weird results. 

Our typical in-situ simulation: 10000+ source dirty input, 4000 source model, perfect calibration. Only gridding out to 60 wavelengths, 2D PS
![fhd_nb_sim_uvf_pskspan60_uvf_1061316296_averemove_bh_dencorr_2dkpower](https://user-images.githubusercontent.com/5588290/34451816-c7bfa994-ece6-11e7-9d1b-3c9aaf45c59b.png)
That doesn't look very good...does anyone remember if this is what a typical uvf input looks like?

The kslices show something strange... Below is the power, and then the weights
![kzslice_power_020](https://user-images.githubusercontent.com/5588290/34451834-346752c2-ece7-11e7-98cd-06437d30f2eb.png)
![kzslice_weights_020](https://user-images.githubusercontent.com/5588290/34451836-47f27470-ece7-11e7-8676-552f0dee707a.png)
The weights look somewhat correct, for the most part. But the power looks wrong...why are the edges so high and choppy?

We of course should rerun this once the uvf input stream is fixed. Again, would love some help.

**Comment by bhazelton** [comment]
I'm actually working on a complete re-work of how settings are passed between the various routines (using structures instead of keywords) which I think will be much more stable and easier to maintain. I'm in the middle of that work right now, how urgent is this? I can try to patch up the existing master if you need it immediately.

**Comment by nicholebarry** [comment]
I'm fairly confident that my hack doesn't affect the above output. I am much more worried about the result. Do you have any idea what is happening?

**Comment by bhazelton** [comment]
My read on this is that the plots look different from our standard ones because of the much finer uv binning (0.5 lambda vs 1.5-3 lambda). So we should look at a coarser gridded uvf input, but I think there's not a major problem here (obviously there is a bookkeeping problem that needs to be fixed.)

**Comment by bhazelton** [comment]
@nicholebarry, can you point me to a recent FHD uvf cube I can work with to test the bookkeeping issues?

**Comment by nicholebarry** [comment]
Sure thing: /nfs/mwa-04/r1/EoRuvfits/analysis/fhd_nb_sim_uvf_pskspan60 has some lightweight uvf cubes.

**Comment by bhazelton** [comment]
Ok, I think the bookkeeping issues are fixed in the latest PR (at least some of them were due to no beamfiles, but that should not have crashed everything).
