### ISSUE TITLE
image_window_name='None' errors

### ISSUE THREAD

**Issue by adampbeardsley** [EoRImaging/eppsilon#46]
Setting `image_window_name='None'` results in an error. It looks like `image_window.pro` uses `spectral_window.pro` to calculate the window function. The former is fine with `'None'`, but the latter does not recognize it. Traceback below.

```% SPECTRAL_WINDOW: Spectral window type not recognized.
% Execution halted at: SPECTRAL_WINDOW    10 /home/beards/MWA/IDL_code/eppsilon/ps_utils/spectral_window.pro
%                      IMAGE_WINDOW        9 /home/beards/MWA/IDL_code/eppsilon/ps_utils/image_window.pro
%                      PS_KCUBE          429 /home/beards/MWA/IDL_code/eppsilon/ps_core/ps_kcube.pro
%                      PS_POWER          172 /home/beards/MWA/IDL_code/eppsilon/ps_core/ps_power.pro
%                      PS_MAIN_PLOTS    1107 /home/beards/MWA/IDL_code/eppsilon/ps_core/ps_main_plots.pro
%                      PS_WRAPPER        163 /home/beards/MWA/IDL_code/eppsilon/ps_wrappers/ps_wrapper.pro
%                      $MAIN$

**Comment by nicholebarry** [comment]
I'd also like to add to this issue. It would be great to have a filename designation for the 'None' filter, since it uses the full cube (I've been using '_large_'  in my recent tests). If the image_window_name isn't set, it uses a small postage stamp instead of the full set, which is definitely what I want in my testing. If there is a filename designation, than it won't overwrite the small postage stamp PS that I make.

**Comment by bhazelton** [comment]
I believe this is fixed in two recent PRs
