### ISSUE TITLE
ps_wrapper requires image_window_frac_size for all windows

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/eppsilon#76]
Running this command:
*ps_wrapper, '/Volumes/Bilbo/rlb_fhd_outputs/array_simulation/fhd_rlb_array_sim_Barry_effect_amp_errors_only_Jul2018', 'hex_array_sim_20m', /png, /refresh_ps, image_window_name = 'Blackman-Harris'*
errors with this message:
*The Healpix image cubes do not extend much beyond the standard window size.
image_window_frac_size must be a value between 0 and 1, using default values.
% Variable is undefined: STD_FRACTION.
% Execution halted at: CHOOSE_PIX_FT     106 /Users/rubybyrne/eppsilon/ps_utils/choose_pix_ft.pro
%                      PS_IMAGE_TO_UVF   254 /Users/rubybyrne/eppsilon/ps_core/ps_image_to_uvf.pro
%                      PS_KCUBE          145 /Users/rubybyrne/eppsilon/ps_core/ps_kcube.pro
%                      PS_POWER           37 /Users/rubybyrne/eppsilon/ps_core/ps_power.pro
%                      PS_MAIN_PLOTS     829 /Users/rubybyrne/eppsilon/ps_core/ps_main_plots.pro
%                      PS_WRAPPER        226 /Users/rubybyrne/eppsilon/ps_wrappers/ps_wrapper.pro
%                      $MAIN$*
Adding the keyword *image_window_frac_size* eliminates the error. However, *image_window_frac_size* should only apply to the Tukey window.

**Comment by bhazelton** [comment]
There are a couple of problems here. I agree that no image window size is required for blackman harris, but it's just ignored in the downstream function, so that wouldn't have errored except that the calculated size was not between 0 & 1. That was probably because these were small images, not large ones. So in the PR referenced above I cleaned up the handling for image window sizes and also improved the warning messages.
