### ISSUE TITLE
deluv in filenames needs to be an input in ps_diff, ps_ratio

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#9]
The UV spacing, deluv, can be set as a parameter during eppsilon. This makes outputs in the ps directory that have that deluv in the name (and rightly so). 

There needs to be an option to add this to the expected names in making ps differences and ps ratios so the right ps outputs can be found. An example ps directory with the naming:

/nfs/mwa-09/r1/djc/EoR2013/Aug23/fhd_nb_decon_March2016_small_through_firstpass_largeind_copy_uv15/ps

An example call:
ps_diff_wrapper, ['fhd_nb_decon_March2016_small_through_firstpass_largeind_copy_uv15','fhd_nb_decon_March2016_small_through_firstpass_largeind_copy_uv15_bh'], ['obs_id_6296','obs_id_6296']

**Comment by bhazelton** [comment]
This should be fixed in latest commit. Note that delta_uv_lambda should be included in the call, so the example should be:

ps_diff_wrapper, ['fhd_nb_decon_March2016_small_through_firstpass_largeind_copy_uv15','fhd_nb_decon_March2016_small_through_firstpass_largeind_copy_uv15_bh'], ['obs_id_6296','obs_id_6296'], delta_uv_lambda=1.5
